# -*- coding: utf-8 -*-
"""project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZrv8pFbWgsWhW4x3jDS0WcTqxt2DSC3
"""

#NPV calculator
investment = float(input("How much did you pay initially?(negative value): "))
rate = float(input("What is the interest rate?(in decimals e.g. 0.05): "))
years = int(input("number of years: "))

cashflows = []
for i in range(years):
    cash = float(input(f"Cashflow for year {i+1}: "))
    cashflows.append(cash)

npv = investment
position = 1  # to track which year we're on

for money in cashflows: # takes each cashflow one by one to perform the next lines
    npv = npv + money / ((1 + rate) ** position)
    position = position + 1

print(f"NPV = ${npv:.2f}")

if npv > 0:
    print("The investment is profitable.")
else:
    print("The investment is not profitable.")

# IRR calculator
investment = float(input("How much is the initial investment(negative number): "))
years = int(input("How many years will the investment be: "))

cashflows = [investment]
for i in range(years):
    cash = float(input(f"cashflow for year {i+1}: "))
    cashflows.append(cash)

def calculate_npv(rate, cashflows):
    npv = 0
    for t in range(len(cashflows)):
        npv = npv + cashflows[t] / ((1 + rate) ** t)
    return npv    # return sends the result out of the function so you can use it. without it, you get None.

def calculate_irr(cashflows):
    rate = 0.1          # guess rate
    tolerance = 0.01    # close enough to zero
    step = 0.0001       # how much to adjust the rate
    iterations = 0      # count how many attempts we made
    npv = calculate_npv(rate, cashflows)
    while abs(npv) > tolerance and iterations < 20000:
        if npv > 0:
            rate += step
        else:
            rate -= step

        npv = calculate_npv(rate, cashflows)  # recalculates NPV with the new rate
        iterations += 1

    return rate

irr = calculate_irr(cashflows)
print("IRR:", round(irr * 100, 3), "%")